version: "3.3"
services:
  php8-cli:
    build: phpdocker
    container_name: php8.1-cli
    volumes:
      - '.:/app'
    tty: true
    stdin_open: true
    restart: unless-stopped
    command: tail -f /dev/null
    environment:
      - TERM=xterm
    networks:
      - my_network

networks:
  my_network:
